GRAPH_START
GRAPH_NODE 0 0
GRAPH_NODE 1 1
GRAPH_NODE 2 2
GRAPH_NODE 3 3
GRAPH_CONNECT 0 1 null false
GRAPH_CONNECT 0 2 null false
GRAPH_CONNECT 1 3 null false
GRAPH_VISIT 0
GRAPH_HIGHLIGHT_EDGE 0 1
GRAPH_HIGHLIGHT_EDGE 0 2
GRAPH_VISIT 1
GRAPH_HIGHLIGHT_EDGE 1 0
GRAPH_HIGHLIGHT_EDGE 1 3
GRAPH_VISIT 2
GRAPH_HIGHLIGHT_EDGE 2 0
GRAPH_VISIT 3
GRAPH_HIGHLIGHT_EDGE 3 1